"""catalog: recipes, ingredients, nutrition_cache, profiles, favorites, seen_history

Revision ID: 0002_catalog
Revises: 0001_baseline
Create Date: 2026-06-08

Adds the six product tables for the catalog/wall/favorites feature on top of the pgvector baseline.
Enums are persisted as constrained strings (CHECK constraints) rather than native PG enums so the
StrEnum values in app.models map 1:1 without migration-time enum juggling. Allergen sets are text[].
Indexes/constraints mirror specs/002-catalog-wall-favorites/data-model.md: UNIQUE(source, source_id),
INDEX(category, is_complete) for browse, favorites composite PK, FKs ON DELETE CASCADE. Written by
hand (not autogenerated) so the array/enum/index choices are explicit and reviewable.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0002_catalog"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create the six catalog tables with their constraints and indexes."""
    # recipes: the grounded corpus; (source, source_id) is the idempotency key, (category, is_complete)
    # backs the browse query.
    op.create_table(
        "recipes",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("cuisine", sa.Text(), nullable=True),
        sa.Column("total_time_minutes", sa.Integer(), nullable=True),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("steps", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("allergens", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("allergen_certain", sa.Boolean(), nullable=False),
        sa.Column("is_vegetarian", sa.Boolean(), nullable=False),
        sa.Column("is_vegan", sa.Boolean(), nullable=False),
        sa.Column("is_pescatarian", sa.Boolean(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_recipes"),
        sa.UniqueConstraint("source", "source_id", name="uq_recipes_source_source_id"),
        sa.CheckConstraint(
            "category IN ('hot_drink', 'cold_drink', 'breakfast', 'lunch', 'dinner')",
            name="ck_recipes_category",
        ),
        sa.CheckConstraint(
            "source IN ('themealdb', 'thecocktaildb', 'kaggle')",
            name="ck_recipes_source",
        ),
    )
    op.create_index("ix_recipes_category_is_complete", "recipes", ["category", "is_complete"])

    # ingredients: parsed lines per recipe; raw_text always retained for provenance.
    op.create_table(
        "ingredients",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("recipe_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("allergen_tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipes.id"], ondelete="CASCADE", name="fk_ingredients_recipe_id"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ingredients"),
    )
    op.create_index("ix_ingredients_recipe_id", "ingredients", ["recipe_id"])

    # nutrition_cache: one row per recipe (PK == FK); precomputed totals for basis_servings.
    op.create_table(
        "nutrition_cache",
        sa.Column("recipe_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("basis_servings", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Numeric(), nullable=False),
        sa.Column("protein_g", sa.Numeric(), nullable=False),
        sa.Column("carbs_g", sa.Numeric(), nullable=False),
        sa.Column("fat_g", sa.Numeric(), nullable=False),
        sa.Column("is_approximate", sa.Boolean(), nullable=False),
        sa.Column("unmapped_ingredient_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipes.id"], ondelete="CASCADE", name="fk_nutrition_cache_recipe_id"
        ),
        sa.PrimaryKeyConstraint("recipe_id", name="pk_nutrition_cache"),
    )

    # profiles: the passwordless cook and constraints; keyed by the X-Profile-ID header value.
    op.create_table(
        "profiles",
        sa.Column("profile_id", sa.Text(), nullable=False),
        sa.Column("diet", sa.Text(), nullable=False, server_default="none"),
        sa.Column("allergies", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("default_servings", sa.Integer(), nullable=False, server_default="2"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("profile_id", name="pk_profiles"),
        sa.CheckConstraint(
            "diet IN ('none', 'vegetarian', 'vegan', 'pescatarian')",
            name="ck_profiles_diet",
        ),
    )

    # favorites: composite PK makes a repeated save a no-op (idempotency, FR-018).
    op.create_table(
        "favorites",
        sa.Column("profile_id", sa.Text(), nullable=False),
        sa.Column("recipe_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.profile_id"], ondelete="CASCADE", name="fk_favorites_profile_id"
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipes.id"], ondelete="CASCADE", name="fk_favorites_recipe_id"
        ),
        sa.PrimaryKeyConstraint("profile_id", "recipe_id", name="pk_favorites"),
    )
    op.create_index("ix_favorites_profile_id", "favorites", ["profile_id"])

    # seen_history: created for the future freshness phase; inert (no reads/writes) this phase.
    op.create_table(
        "seen_history",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("profile_id", sa.Text(), nullable=False),
        sa.Column("recipe_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("shown_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.profile_id"], ondelete="CASCADE", name="fk_seen_history_profile_id"
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipes.id"], ondelete="CASCADE", name="fk_seen_history_recipe_id"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_seen_history"),
    )
    op.create_index("ix_seen_history_profile_shown", "seen_history", ["profile_id", "shown_at"])


def downgrade() -> None:
    """Drop the six catalog tables in reverse dependency order (children before parents)."""
    op.drop_index("ix_seen_history_profile_shown", table_name="seen_history")
    op.drop_table("seen_history")
    op.drop_index("ix_favorites_profile_id", table_name="favorites")
    op.drop_table("favorites")
    op.drop_table("profiles")
    op.drop_table("nutrition_cache")
    op.drop_index("ix_ingredients_recipe_id", table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index("ix_recipes_category_is_complete", table_name="recipes")
    op.drop_table("recipes")
