"""cook_accounts: named, admin-provisioned cook logins + re-key of cook-owned data (009)

Revision ID: 0005_cook_accounts
Revises: 0004_operator_accounts
Create Date: 2026-06-15

Replaces the passwordless `X-Profile-ID` identity with a named cook account. Creates `cook_accounts`
(opaque string id = the owner key, unique username, bcrypt hash, NO role) and re-keys the cook-owned
tables to it: `profiles.profile_id` becomes a FK → `cook_accounts.id` (ON DELETE CASCADE), so deleting a
cook cascades through its profile to its favorites/seen_history. Because both sides are `Text`, this adds
ONE FK without altering any column type across the three tables (data-model.md, the minimal-churn re-key).

⚠️ IRREVERSIBLE DATA WIPE (FR-015, fresh start): existing anonymous `profiles`/`favorites`/`seen_history`
rows are keyed by client-generated profile-IDs that cannot satisfy the new FK, so `upgrade()` DELETEs them
before adding the constraint. `downgrade()` drops the FK + table but does NOT restore that deleted data —
back up before applying on any environment with real data (surfaced in RUNBOOK per task T029).
`operator_accounts` (008) and all recipe/embedding tables are untouched. Written by hand so the data wipe
+ FK ordering are explicit.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0005_cook_accounts"
down_revision = "0004_operator_accounts"
branch_labels = None
depends_on = None

# Name the FK explicitly so downgrade() drops it deterministically (autogenerated names differ by backend).
_PROFILES_COOK_FK = "fk_profiles_profile_id_cook_accounts"


def upgrade() -> None:
    """Create cook_accounts, clear ownerless anonymous rows, then FK profiles.profile_id → cook_accounts.id."""
    op.create_table(
        "cook_accounts",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    # UNIQUE index on username is both the DB-level uniqueness backstop (FR-006) and the login lookup path.
    op.create_index("ix_cook_accounts_username", "cook_accounts", ["username"], unique=True)

    # Fresh start (FR-015): existing anonymous rows are keyed by client-generated profile-IDs that cannot
    # satisfy the new FK to cook_accounts. Clear children before parents so each DELETE respects existing
    # FKs (favorites/seen_history → profiles). ⚠️ This data is NOT recoverable via downgrade().
    op.execute("DELETE FROM seen_history")
    op.execute("DELETE FROM favorites")
    op.execute("DELETE FROM profiles")

    # Re-key: profile ownership now references a real cook account; deleting a cook cascades to its data.
    op.create_foreign_key(
        _PROFILES_COOK_FK,
        "profiles",
        "cook_accounts",
        ["profile_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Drop the FK, the username index, and the table (reverse of upgrade).

    ⚠️ Does NOT restore the `profiles`/`favorites`/`seen_history` rows that upgrade() wiped — that data is
    gone (FR-015 fresh start). Downgrade only removes the cook-account schema, leaving the cook tables empty.
    """
    op.drop_constraint(_PROFILES_COOK_FK, "profiles", type_="foreignkey")
    op.drop_index("ix_cook_accounts_username", table_name="cook_accounts")
    op.drop_table("cook_accounts")
